spring.application.name=loan-support-service
server.port=8090

spring.datasource.url=jdbc:mysql://localhost:3306/loan_support_db
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD:root}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.hostname=localhost
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

# SAME secret key as all other services
jwt.secret=${JWT_SECRET:myfinbanksecretkeymyfinbanksecretkey123456}
jwt.expiration=86400000
